version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build -t eyenx/aurbuilder . 
      - run:
          name: Test Image
          command: |
            docker run eyenx/aurbuilder tty-clock
      - run:
          name: Push Image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin && docker tag eyenx/aurbuilder:latest eyenx/aurbuilder:$CIRCLE_SHA1 && docker push eyenx/aurbuilder:latest && docker push eyenx/aurbuilder:$CIRCLE_SHA1
